openapi: 3.0.2
info:
  title: Variants Example
  version: 0.0.0
paths:
  /ref-response-body:
    get:
      operationId: getRefResponseBody
      responses:
        '200':
          $ref: '#/components/responses/RefResponse'
  /inline-request-body:
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - itemName
                properties:
                  itemName:
                    type: string
      responses:
        "204":
          description: No Content
  /inline-response-body:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
          description: "Ok"
components:
  responses:
    RefResponse:
      description: A ref response
      content:
        application/json:
          schema:
            required:
              - refResponseDescription
            type: object
            properties:
              refResponseDescription:
                type: string
  schemas:
    RequiredAndNullable:
      type: object
      required:
        - requiredNullable
        - requiredNonNullable
      properties:
        requiredNullable:
          type: string
          nullable: true
        requiredNonNullable:
          type: string
        optionalNullable:
          type: string
          nullable: true
        optionalNonNullable:
          type: string
    AdditionalPropertiesWithOtherProperties:
      type: object
      properties:
        name:
          type: string
      required:
        - name
      additionalProperties: true
    AdditionalPropertiesEmptyObject:
      type: object
      additionalProperties: {}
    AdditionalPropertiesTrue:
      type: object
      additionalProperties: true
    ObjectWithRefToPrimitive:
      type: object
      properties:
        key:
          $ref: "#/components/schemas/PrimitiveKey"
      required:
        - key
    PrimitiveKey:
      type: integer
    AllOfTwoObjects:
      allOf:
        - $ref: "#/components/schemas/AllOfFirstObject"
        - $ref: "#/components/schemas/AllOfSecondObject"
    AllOfFirstObject:
      type: object
      properties:
        name2:
          type: string
      required:
        - name2
    AllOfSecondObject:
      type: object
      properties:
        age:
          type: integer
      required:
        - age
    UseMixedAllOf:
      type: object
      required:
        - mixed
      properties:
        mixed:
          $ref: "#/components/schemas/MixedAllOf"
    MixedAllOf:
        allOf:
          - type: number
          - type: integer
    PagingObject:
      type: object
      x-spotify-docs-type: PagingObject
      required:
        - href
        - items
        - limit
        - next
      properties:
        href:
          type: string
        limit:
          type: integer
        next:
          type: string
          nullable: true
    PagingThingObject:
      type: object
      x-spotify-docs-type: PagingArtistObject
      allOf:
        - $ref: "#/components/schemas/PagingObject"
        - type: object
          properties:
            items:
              type: array
              items:
                type: string
    Vehicle:
      oneOf:
        - $ref: "#/components/schemas/Car"
        - $ref: "#/components/schemas/Bike"
      discriminator:
        propertyName: type
    Car:
      type: object
      required:
        - type
        - brand
      properties:
        type:
          type: string
          enum:
            - car
        brand:
          type: string
    Bike:
      type: object
      required:
        - type
        - model
      properties:
        type:
          type: string
          enum:
            - bike
        model:
          type: string
